
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "ollama serve &
      sleep 10
      ollama run llama3.1:8b
      while true; do sleep 1; done"
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - rag-network

  backend:
    build: ./backend
    environment:
      - API_USER=admin
      - API_PASS=secret
      - OLLAMA_HOST=ollama:11434
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rag-network

  gradio:
    build: ./gradio_app
    ports:
      - "3000:7860"
    depends_on:
      - backend
    networks:
      - rag-network

volumes:
  ollama:

networks:
  rag-network:
    driver: bridge